### ISSUE TITLE
Some errors in making release 16

### ISSUE THREAD

**Issue by naderzare** [rcsoccersim/rcssmonitor#13]
**I installed QT5 and my moc version is 5.9.7 in ubuntu 16.04,**
**But in make process I saw these errors:**
make  all-recursive
make[1]: Entering directory '/home/nader/workspace/robo/rcssmonitor'
Making all in src
make[2]: Entering directory '/home/nader/workspace/robo/rcssmonitor/src'
g++ -std=c++14 -DHAVE_CONFIG_H -I. -I..  -I.. -I../src  -I/usr/include -W -Wall -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5 -fPIC -g -O2 -MT rcssmonitor-moc_player_type_dialog.o -MD -MP -MF .deps/rcssmonitor-moc_player_type_dialog.Tpo -c -o rcssmonitor-moc_player_type_dialog.o `test -f 'moc_player_type_dialog.cpp' || echo './'`moc_player_type_dialog.cpp
moc_player_type_dialog.cpp:22:1: error: ‘QT_WARNING_DISABLE_DEPRECATED’ does not name a type
 QT_WARNING_DISABLE_DEPRECATED
 ^
moc_player_type_dialog.cpp:32:14: error: ‘qt_meta_stringdata_PlayerTypeDialog_t’ does not name a type
 static const qt_meta_stringdata_PlayerTypeDialog_t qt_meta_stringdata_PlayerTypeDialog = {
              ^
moc_player_type_dialog.cpp:79:35: error: ‘qt_meta_stringdata_PlayerTypeDialog’ was not declared in this scope
     { &QDialog::staticMetaObject, qt_meta_stringdata_PlayerTypeDialog.data,
                                   ^
moc_player_type_dialog.cpp: In member function ‘virtual void* PlayerTypeDialog::qt_metacast(const char*)’:
moc_player_type_dialog.cpp:92:26: error: ‘qt_meta_stringdata_PlayerTypeDialog’ was not declared in this scope
     if (!strcmp(_clname, qt_meta_stringdata_PlayerTypeDialog.stringdata0))
                          ^
Makefile:1002: recipe for target 'rcssmonitor-moc_player_type_dialog.o' failed
make[2]: *** [rcssmonitor-moc_player_type_dialog.o] Error 1
make[2]: Leaving directory '/home/nader/workspace/robo/rcssmonitor/src'
Makefile:419: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/nader/workspace/robo/rcssmonitor'
Makefile:360: recipe for target 'all' failed
make: *** [all] Error 2

**I removed QT_WARNING_DISABLE_DEPRECATED from all files, I didn't see any errors and monitor works very good with server 16.**

**Comment by hidehisaakiyama** [comment]
If you have not cleaned old moc_* files generated by Qt4, this problem may be occurred.
Try `make distclean`, then `configure && make` again.

If you are using release-16.0 branch, CMake may be a better solution.
Please try the following commands in the package directory:
```
mkdir build
cd build
cmake ..
make
```
