### ISSUE TITLE
Autoconf error

### ISSUE THREAD

**Issue by marcinic** [rcsoccersim/rcssmonitor#2]
when I type ./configure and then make I get the following error

g++: error: unrecognized command line option ‘-pthread-lQtGui’; did you mean ‘-fthread-jumps’?
Makefile:477: recipe for target 'rcssmonitor' failed
make[2]: *** [rcssmonitor] Error 1
make[2]: Leaving directory '/home/marcinic/hdd/Programs/rcssmonitor-15.2.0/src'
Makefile:382: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/marcinic/hdd/Programs/rcssmonitor-15.2.0'
Makefile:322: recipe for target 'all' failed
make: *** [all] Error 2

In configure.status  there is a space missing between -pthread -lQtGui
configure: set QT4_LDADD... -pthread-lQtGui -lQtCore -lfontconfig -lpthread -laudio -lXt -lgthread-2.0 -lglib-2.0 -lpng -lz -lfreetype -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXi -lXrender -lfontconfig -lfreetype -lXext -lX11 -lm -lQtNetwork -lQtCore -lfontconfig -lpthread -lz -lQtCore -lfontconfig -lpthread -lz -lm -ldl -lgthread-2.0 -lglib-2.0 -lrt

**Comment by hidehisaakiyama** [comment]
Please use rcssmonitor-15.2.1 or later.
https://github.com/rcsoccersim/rcssmonitor/releases

**Comment by marcinic** [comment]
Thanks
