### ISSUE TITLE
Status of SoccerWindow2 project

### ISSUE THREAD

**Issue by herodrigues** [rcsoccersim/rcssmonitor#3]
HI @hidehisaakiyama 

Since SoccerWindow2 is used in the finals and it seems to have more features than rcssmonitor, what's the status of the project and why it's not here in this organization?

**Comment by hidehisaakiyama** [comment]
soccerwindow2 is  my own project, not a robocup official monitor/logplayer. I have no plan to introduce soccerwindow2 as an official product. If some features are useful, easy to import, and easy to maintain, they may be introduced to rcssmonitor.

**Comment by herodrigues** [comment]
Ah ok! I thought it was an official monitor.
