### ISSUE TITLE
monitor not compiling on Debian 11 - issue with QT libs

### ISSUE THREAD

**Issue by smixxer** [rcsoccersim/rcssmonitor#32]
Hello,
I could compile and run the "server" and the "sampleClient", but could not compile the "monitor":

![Schermata da 2022-03-31 09-42-12](https://user-images.githubusercontent.com/102723862/161006298-9187af8f-05c1-41cf-bef9-0b1db1f0e419.png)

how to fix that?

**Comment by hidehisaakiyama** [comment]
I'm not familiar with Debian.
In the case of Ubuntu, you can just type the following to install depending libraries:

`sudo apt install build-essential libboost-all-dev qt5-default libfontconfig1-dev libaudio-dev libxt-dev libglib2.0-dev libxi-dev libxrender-dev`

Please check the latest [README](https://github.com/rcsoccersim/rcssmonitor/blob/master/README.md).

**Comment by smixxer** [comment]
> 

Hi,
I was doing what recommended in the README you mentioned.

Unfortunately, package **qt5-default** is not available on debian, not sure how to deal with that...

**Comment by hidehisaakiyama** [comment]
It's difficult for me to answer this problem because I don't use the latest Debian.
https://forum.qt.io/topic/132190/issue-with-sudo-apt-get-install-qt5-default/2 may help you.

**Comment by smixxer** [comment]
> It's difficult for me to answer this problem because I don't use the latest Debian. https://forum.qt.io/topic/132190/issue-with-sudo-apt-get-install-qt5-default/2 may help you.

it's now working: qtbase5-dev was the package needed

thx, you can close the issue to me.
