### ISSUE TITLE
CMake build system ignores user supplied CMAKE_CXX_FLAGS

### ISSUE THREAD

**Issue by hedayat** [rcsoccersim/rcssmonitor#37]
[This line](https://github.com/rcsoccersim/rcssmonitor/blob/ea35f2aadaac3f0440687cb2691bcfd414808e5f/CMakeLists.txt#L16) in CMakeLists.txt overwrites any user supplied values which is not desirable. A minimum change would be to append values to this variable; more suitable approach is probably to change default values and let the user decide if he wants to use the default ones or not. An example of the latter approach is [available here](https://github.com/hedayat/powerfake/blob/2969a9f4f3b015c70586bb34433e81bbdf4b64b2/CMakeLists.txt#L7).

Same problem exists in rcssserver project.

**Comment by hedayat** [comment]
To be honest, I don't know the answer to your first question! There *might* be someone who prefers to not see the warnings; but it might not be a priority. 

But yeah, that'd work in that case but it seems that the scope argument is mandatory: `target_compile_options(rcssmonitor PRIVATE -W -Wall)`

**Comment by hidehisaakiyama** [comment]
OK. Thanks.
Will be fixed soon.
