### ISSUE TITLE
Building fails when running "make"

### ISSUE THREAD

**Issue by AtomScott** [rcsoccersim/rcssmonitor#4]
I'm trying to build the rcssmonitor after running "./configure" but I get the following error on the ubuntu 18.04 machine I am using.

```
me@mypcr:~/rcssmonitor$ make
make  all-recursive
make[1]: Entering directory '/home/member/rcssmonitor'
Making all in src
make[2]: Entering directory '/home/member/rcssmonitor/src'
g++ -W -Wall -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I/usr/include/qt4/QtCore -g -O2 -L/usr/X11R6/lib64 -L/usr/lib/x86_64-linux-gnu -o rcssmonitor rcsslogplayer/rcssmonitor-parser.o rcsslogplayer/rcssmonitor-types.o rcsslogplayer/rcssmonitor-util.o rcssmonitor-angle_deg.o rcssmonitor-ball_painter.o rcssmonitor-circle_2d.o rcssmonitor-config_dialog.o rcssmonitor-disp_holder.o rcssmonitor-draw_info_painter.o rcssmonitor-field_canvas.o rcssmonitor-field_painter.o rcssmonitor-line_2d.o rcssmonitor-log_player.o rcssmonitor-main_window.o rcssmonitor-monitor_client.o rcssmonitor-options.o rcssmonitor-player_painter.o rcssmonitor-player_type_dialog.o rcssmonitor-score_board_painter.o rcssmonitor-team_graphic.o rcssmonitor-team_graphic_painter.o rcssmonitor-vector_2d.o rcssmonitor-main.o rcssmonitor-moc_config_dialog.o rcssmonitor-moc_field_canvas.o rcssmonitor-moc_log_player.o rcssmonitor-moc_main_window.o rcssmonitor-moc_monitor_client.o rcssmonitor-moc_player_type_dialog.o -lboost_program_options -pthread -lQtGui -lQtCore -lfontconfig -lpthread -laudio -lXt -lgthread-2.0 -lglib-2.0 -lpng -lz -lfreetype -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXi -lXrender -lfontconfig -lfreetype -lXext -lX11 -lm -lQtNetwork -lQtCore -lfontconfig -lpthread -lz -lQtCore -lfontconfig -lpthread -lz -lm -ldl -lgthread-2.0 -lglib-2.0 -lrt -lz -lm 
/usr/bin/ld: cannot find -lfontconfig
collect2: error: ld returned 1 exit status
Makefile:488: recipe for target 'rcssmonitor' failed
make[2]: *** [rcssmonitor] Error 1
make[2]: Leaving directory '/home/member/rcssmonitor/src'
Makefile:392: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/member/rcssmonitor'
Makefile:333: recipe for target 'all' failed
make: *** [all] Error 2

```

I was able to install the soccer server without any problem by following the instructions, but I am stuck here.

Any help wil be helpful.

**Comment by Afshari9978** [comment]
you should install following packages from apt using this command:

`sudo apt install libfontconfig1 fontconfig libfontconfig1-dev fontconfig-config libxi-dev libaudio-dev libxrender-dev`

**Comment by AtomScott** [comment]
Thank you, running the command solved the problem.

**Comment by ProgramPaNo18** [comment]
Hi i tried and installed those packages but still i cant make the project
here is the error:
`make  all-recursive
make[1]: Entering directory '/home/pano/Desktop/2D/Monitor/rcssmonitor-15.2.1'
Making all in src
make[2]: Entering directory '/home/pano/Desktop/2D/Monitor/rcssmonitor-15.2.1/src'
g++ -W -Wall -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I/usr/include/qt4/QtCore -g -O2 -L/usr/X11R6/lib64 -L/usr/lib/x86_64-linux-gnu -o rcssmonitor rcsslogplayer/rcssmonitor-parser.o rcsslogplayer/rcssmonitor-types.o rcsslogplayer/rcssmonitor-util.o rcssmonitor-angle_deg.o rcssmonitor-ball_painter.o rcssmonitor-circle_2d.o rcssmonitor-config_dialog.o rcssmonitor-disp_holder.o rcssmonitor-draw_info_painter.o rcssmonitor-field_canvas.o rcssmonitor-field_painter.o rcssmonitor-line_2d.o rcssmonitor-log_player.o rcssmonitor-main_window.o rcssmonitor-monitor_client.o rcssmonitor-options.o rcssmonitor-player_painter.o rcssmonitor-player_type_dialog.o rcssmonitor-score_board_painter.o rcssmonitor-team_graphic.o rcssmonitor-team_graphic_painter.o rcssmonitor-vector_2d.o rcssmonitor-main.o rcssmonitor-moc_config_dialog.o rcssmonitor-moc_field_canvas.o rcssmonitor-moc_log_player.o rcssmonitor-moc_main_window.o rcssmonitor-moc_monitor_client.o rcssmonitor-moc_player_type_dialog.o -lboost_program_options -pthread -lQtGui -lQtCore -lfontconfig -lpthread -laudio -lXt -lgthread-2.0 -lglib-2.0 -lpng -lz -lfreetype -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXi -lXrender -lfontconfig -lfreetype -lXext -lX11 -lm -lQtNetwork -lQtCore -lfontconfig -lpthread -lz -lQtCore -lfontconfig -lpthread -lz -lm -ldl -lgthread-2.0 -lglib-2.0 -lrt -lz -lm 
/usr/bin/ld: cannot find -lXt
/usr/bin/ld: cannot find -lSM
/usr/bin/ld: cannot find -lICE
collect2: error: ld returned 1 exit status
Makefile:488: recipe for target 'rcssmonitor' failed
make[2]: *** [rcssmonitor] Error 1
make[2]: Leaving directory '/home/pano/Desktop/2D/Monitor/rcssmonitor-15.2.1/src'
Makefile:392: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pano/Desktop/2D/Monitor/rcssmonitor-15.2.1'
Makefile:333: recipe for target 'all' failed
make: *** [all] Error 2
`
I have Linux Mint 19.3 Bionic and i think this is a problem with all bionic versions of linux
